# Generated by Django 4.2.5 on 2023-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_level_user_interaction_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="/MyBlogProject/media/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
