# Generated by Django 4.2.6 on 2023-10-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categori',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate_chill', to='blog.categori'),
        ),
    ]
