# Generated by Django 4.2.5 on 2023-10-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_categori_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="static/images"),
        ),
    ]
